---
user: "{{ lookup('env','USER') }}"
password: passw0rd

demo_pass: "{{ password }}"
admin_pass: "{{ password }}"
glance_pass: "{{ password }}"
nova_pass: "{{ password }}"
neutron_pass: "{{ password }}"
rabbit_pass: "{{ password }}"
metadata_secret: "{{ password }}"

keystone_dbpass: "{{ password }}"
glance_dbpass: "{{ password }}"
nova_dbpass: "{{ password }}"
neutron_dbpass: "{{ password }}"
root_dbpass: "{{ password }}"

